"""
Collect demonstration episodes from the MuJoCo scene into LeRobot dataset
format, ready for `lerobot-train --policy.path=lerobot/smolvla_base ...`.

Trajectories are generated by IK (mink), not sine sweeps: for each training
seed, `build_drawer_and_cutlery_episode` reads where DomainRandomizer actually
placed the drawer and objects, solves IK to those real coordinates, and
returns a joint-space trajectory. No manual per-seed tuning.

Seed discipline: episodes are recorded using ONLY seeds from
randomization.yaml `training.seed_range` -- never the 10 reserved eval seeds.
"""
import os
os.environ["SVT_LOG"] = "0"
import sys
import numpy as np
import mujoco
from lerobot.datasets.lerobot_dataset import LeRobotDataset


sys.path.insert(0, "sim")
sys.path.insert(0, ".")  # for scripted_episode_ik and ik_demo_utils
from randomization import DomainRandomizer  # noqa: E402
from scripted_episode_ik import build_drawer_and_cutlery_episode  # noqa: E402

MODEL_PATH = "sim/assets/dinner_table_dual_so101.xml"
RANDOMIZATION_CFG = "configs/randomization.yaml"
FPS = 30

# Every actuator, in a fixed order -- this fixed order IS the 12-dim
# action/state vector layout every other component (policy, inference
# runtime) must agree on.
ACTUATOR_NAMES = [
    "left_shoulder_pan",
    "left_shoulder_lift",
    "left_elbow_flex",
    "left_wrist_flex",
    "left_wrist_roll",
    "left_gripper",
    "right_shoulder_pan",
    "right_shoulder_lift",
    "right_elbow_flex",
    "right_wrist_flex",
    "right_wrist_roll",
    "right_gripper",
]

CAMERA_SPECS = {
    "overhead": (320, 240),
    "wrist_left": (160, 120),
    "wrist_right": (160, 120),
}


def build_features():
    features = {
        "action": {
            "dtype": "float32",
            "shape": (len(ACTUATOR_NAMES),),
            "names": ACTUATOR_NAMES,
        },
        "observation.state": {
            "dtype": "float32",
            "shape": (len(ACTUATOR_NAMES),),
            "names": ACTUATOR_NAMES,
        },
    }
    for cam_name, (w, h) in CAMERA_SPECS.items():
        features[f"observation.images.{cam_name}"] = {
            "dtype": "video",
            "shape": (h, w, 3),
            "names": ["height", "width", "channels"],
        }
    return features


def get_joint_state(model, data):
    """Read back the 12 actuated joint positions, in ACTUATOR_NAMES order --
    NOT the raw qpos array, since qpos includes free-joint object states too
    and isn't in a stable, policy-relevant order."""
    state = np.zeros(len(ACTUATOR_NAMES), dtype=np.float32)
    for i, act_name in enumerate(ACTUATOR_NAMES):
        act_id = model.actuator(act_name).id
        joint_id = model.actuator_trnid[act_id, 0]
        qpos_adr = model.jnt_qposadr[joint_id]
        state[i] = data.qpos[qpos_adr]
    return state


def render_all_cameras(renderers, data):
    frames = {}
    for cam_name, renderer in renderers.items():
        renderer.update_scene(data, camera=cam_name)
        frames[cam_name] = renderer.render()
    return frames


def _apply_qpos_to_ctrl(model, data, qpos):
    """Write a full qpos array into data.ctrl targets for the 12 actuators.
    Position actuators (gainprm ~998) treat ctrl as a target joint angle,
    so qpos[joint] -> ctrl[actuator] is a direct copy."""
    for act_name in ACTUATOR_NAMES:
        act_id = model.actuator(act_name).id
        joint_id = model.actuator_trnid[act_id, 0]
        qpos_adr = model.jnt_qposadr[joint_id]
        data.ctrl[act_id] = qpos[qpos_adr]


def collect(n_episodes, repo_id, root, instruction, control_decimation=10, seed_offset=0):
    model = mujoco.MjModel.from_xml_path(MODEL_PATH)
    data = mujoco.MjData(model)
    randomizer = DomainRandomizer(model, RANDOMIZATION_CFG)

    renderers = {name: mujoco.Renderer(model, height=h, width=w)
                 for name, (w, h) in CAMERA_SPECS.items()}

    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        fps=FPS,
        features=build_features(),
        root=root,
        robot_type="dual_so101",
        use_videos=True,
    )

    seed_rng = np.random.RandomState(seed_offset)
    used_seeds = []

    for ep in range(n_episodes):
        seed = randomizer.sample_training_seed(seed_rng)
        assert not randomizer.is_eval_seed(seed), (
            f"sampled seed {seed} collides with a reserved eval seed -- "
            "this should be impossible given disjoint ranges; stop and check "
            "configs/randomization.yaml training.seed_range"
        )
        used_seeds.append(seed)

        # 1. Reset scene with this seed (places objects, sets drawer state)
        randomizer.reset(data, seed)
        mujoco.mj_forward(model, data)

        # 2. Build IK-based trajectory from the ACTUAL scene state this seed
        print(f"[collect] building IK trajectory for seed={seed}...")
        qpos_trace, gripper_trace = build_drawer_and_cutlery_episode(
            model, data, randomizer
        )
        print(f"[collect] trajectory: {len(qpos_trace)} steps, "
              f"cutlery-in-drawer={sorted(randomizer.last_in_drawer_items)}")

        # 3. Step through the trace, applying ctrl targets and recording
        for step_idx in range(len(qpos_trace)):
            _apply_qpos_to_ctrl(model, data, qpos_trace[step_idx])

            # Override gripper joint target with the discrete open/close value
            gval = gripper_trace[step_idx]
            if gval is not None:
                right_gripper_act_id = model.actuator("right_gripper").id
                data.ctrl[right_gripper_act_id] = gval

            for _ in range(control_decimation):
                mujoco.mj_step(model, data)

            state = get_joint_state(model, data)
            frames = render_all_cameras(renderers, data)
            frame = {
                "action": data.ctrl.copy()[: len(ACTUATOR_NAMES)].astype(np.float32),
                "observation.state": state,
                "task": instruction,
            }
            for cam_name, img in frames.items():
                frame[f"observation.images.{cam_name}"] = img
            dataset.add_frame(frame)

        dataset.save_episode()
        print(f"[collect] episode {ep+1}/{n_episodes} recorded (seed={seed})")

    dataset.finalize()
    print(f"\nWrote {n_episodes} episodes to {root}")
    print(f"Training seeds used (first 10 shown): {used_seeds[:10]}"
          + (" ..." if len(used_seeds) > 10 else ""))
    return dataset


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", type=int, default=3)
    parser.add_argument("--repo-id", type=str, default="local/dinner_table_ik")
    parser.add_argument("--root", type=str, default="./data/demo_dataset")
    parser.add_argument("--instruction", type=str,
                         default="open the drawer, retrieve the cutlery, close the drawer, set the table")
    parser.add_argument("--seed-offset", type=int, default=0)
    args = parser.parse_args()

    collect(args.episodes, args.repo_id, args.root, args.instruction,
             seed_offset=args.seed_offset)